
FROM --platform=$BUILDPLATFORM php:8.3.7-apache
#RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
#RUN docker-php-ext-install mysqli pdo pdo_mysql
#RUN docker-php-ext-enable mysqli pdo pdo_mysql
#RUN apt-get update && apt-get upgrade -y
#RUN apt-get install nano
